version: "3.9"

services:
  fastapi-db:
    image: postgres:16
    container_name: fastapi-db
    environment:
      POSTGRES_DB: cochesdb
      POSTGRES_USER: quevedo
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U quevedo -d cochesdb"]
      interval: 5s
      timeout: 5s
      retries: 10

  fastapi-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi-app
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      fastapi-db:
        condition: service_healthy
